insert into user (user_id, role, username, name, email, password) values (0, 0, 'andyDC', 'Angy Pita', 'angy.da.cruz@hotmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (1, 0, 'dawnofdom', 'Domingos Santos', 'domingosjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (2, 0, 'luisrelvas', 'Luis Relvas', 'luisrelvas@hotmail.com', 1234)


insert into user (user_id, role, username, name, email, password) values (3, 1, 'aaaaaa', 'Domingos Santos', 'omingosjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (4, 1, 'bbbbb', 'Domingos Santos', 'dmingosjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (5, 1, 'ccccc', 'Domingos Santos', 'doingosjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (6, 1, 'ddddd', 'Domingos Santos', 'domngosjsmsantos@gmail.com', 1234)

insert into user (user_id, role, username, name, email, password) values (7, 2, 'eeeee', 'Domingos Santos', 'domigosjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (8, 2, 'fffff', 'Domingos Santos', 'dominosjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (9, 2, 'gggg', 'Domingos Santos', 'domingsjsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (10, 2, 'hhhh', 'Domingos Santos', 'domingojsmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (11, 2, 'iiiii', 'Domingos Santos', 'domingossmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (12, 2, 'jjjjjj', 'Domingos Santos', 'domingosjmsantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (13, 2, 'kkkkk', 'Domingos Santos', 'domingosjssantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (14, 2, 'lllll', 'Domingos Santos', 'domingosjsmantos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (15, 2, 'mmmmm', 'Domingos Santos', 'domingosjsmsntos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (16, 2, 'nnnnnn', 'Domingos Santos', 'domingosjsmsatos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (17, 2, 'oooooo', 'Domingos Santos', 'domingosjsmsanos@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (18, 2, 'ppppp', 'Domingos Santos', 'domingosjsmsants@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (19, 2, 'qqqqq', 'Domingos Santos', 'domingosjsmsanto@gmail.com', 1234)
insert into user (user_id, role, username, name, email, password) values (20, 2, 'rrrrr', 'Domingos Santos', 'domingosjsmsantosss@gmail.com', 1234)

insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (0, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (1, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (2, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (3, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (4, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (5, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (6, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (7, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (8, 7, 0, 0, '', '', "01/01/1111")
insert into ticket (ticket_id, user_id, department_id, status_id, title, description, initial_date) values (9, 7, 0, 0, '', '', "01/01/1111")

insert into status (status_id, name, open, assigned, closed) values (0, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (1, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (2, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (3, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (4, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (5, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (6, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (7, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (8, '', 0, 0, 0)
insert into status (status_id, name, open, assigned, closed) values (9, '', 0, 0, 0)

insert into department (department_id, name) values (1, '')
insert into department (department_id, name) values (2, '')
insert into department (department_id, name) values (3, '')
insert into department (department_id, name) values (4, '')
insert into department (department_id, name) values (5, '')
insert into department (department_id, name) values (6, '')
insert into department (department_id, name) values (7, '')
insert into department (department_id, name) values (8, '')
insert into department (department_id, name) values (9, '')
insert into department (department_id, name) values (10, '')

insert into hashtag (hashtag_id, tag) values(0, '')
insert into hashtag (hashtag_id, tag) values(1, '')
insert into hashtag (hashtag_id, tag) values(2, '')
insert into hashtag (hashtag_id, tag) values(3, '')
insert into hashtag (hashtag_id, tag) values(4, '')
insert into hashtag (hashtag_id, tag) values(5, '')
insert into hashtag (hashtag_id, tag) values(6, '')
insert into hashtag (hashtag_id, tag) values(7, '')
insert into hashtag (hashtag_id, tag) values(8, '')
insert into hashtag (hashtag_id, tag) values(9, '')

